name: Laravel
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to DigitalOcean Droplet
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DOHOST }}   # Bu yerda DOHOST ishlatiladi
          username: ${{ secrets.DOUSERNAME }}
          key: ${{ secrets.DOKEY }}
          script: |
            cd /var/www/nt-online-market
            sudo docker compose down
            sudo git reset --hard
            sudo git pull origin main
            sudo docker compose up -d --build
            sleep 2
            sudo docker exec market_app php artisan migrate --force
            sudo docker exec market_app php artisan optimize
            echo "✅ Deploy to DigitalOcean completed!"
