name: Laravel
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to AWS (EC2)
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/OnlineMarketApp
            sudo docker compose down
            sudo git reset --hard
            sudo git pull
            sudo docker compose up -d --build
            sleep 2
            sudo docker exec market_app php artisan migrate
            sudo docker exec market_app php artisan optimize
             sudo docker exec market_app chmod -R 775 /var/www
            echo "Deploy Completed!"
